import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar del segundo libro: "Inglés para Ingenieros".
 *
 * Misma decisión que en el libro de ingeniería (ver sidebars.ts): el árbol
 * es 100% autogenerado desde la estructura de carpetas de /english, con
 * `_category_.json` para labels y orden. Aquí el orden importa todavía más
 * que en el libro técnico — este libro está diseñado para leerse en
 * secuencia (Módulo 0 → 5), no por picoteo, así que las carpetas van
 * numeradas y `position` refleja el orden real del curso.
 */
const sidebarsEnglish: SidebarsConfig = {
  englishSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsEnglish;
