import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * DECISIÓN ARQUITECTÓNICA:
 *
 * El sidebar es 100% autogenerado a partir de la estructura de carpetas
 * en /docs, usando archivos `_category_.json` para labels, orden y
 * descripciones. NO mantenemos un árbol manual aquí.
 *
 * Por qué: en un proyecto que crecerá durante 10 años y cientos de temas,
 * un sidebars.ts manual se convierte en el archivo más doloroso de
 * mantener — cada tema nuevo obliga a editarlo, y es fácil olvidar
 * agregarlo (el tema queda "huérfano", visible por URL pero invisible
 * en la navegación). Con autogenerated, agregar un tema es simplemente
 * crear el .md correcto en la carpeta correcta.
 *
 * `intro.md` tiene `sidebar_position: 0` y `slug: /`, así que aparece
 * primero automáticamente — no hace falta listarlo aquí.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
